# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: GOLEM - a MOOSE-based application
email: antoine.jacquey@gfz-potsdam.de
description: > # this means to ignore newlines until "baseurl:"
GOLEM is a numerical simulator for modelling coupled Thermo-Hydro-Mechanical
processes in faulted geothermal reservoirs.
baseurl: "/home" # the subpath of your site, e.g. /blog
url: "https://ajacquey.github.io/Golem/" # the base hostname & protocol for your site
twitter_username: antoine_jacquey 
github_username:  ajacquey

# Build settings
markdown: kramdown
kramdown:
  input: GFM

# Third-party services
# just leave someone empty to disable it
# google_analytics: 
disqus_shortname:

# used this for post_excerpt at index_page
excerpt_separator: <!--description-->
