# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: GOLEM - a MOOSE-based application
email: antoine.jacquey@gfz-potsdam.de
description: > # this means to ignore newlines until "baseurl:"
GOLEM is a numerical simulator for modelling coupled Thermo-Hydro-Mechanical
processes in faulted geothermal reservoirs. The simulator is developed by
[Antoine Jacquey](http://www.gfz-potsdam.de/en/staff/antoine-jacquey/) <a
href="https://orcid.org/0000-0002-6259-4305" target="orcid.widget" rel="noopener
noreferrer" style="vertical-align:top;"><img
src="https://orcid.org/sites/default/files/images/orcid_16x16.png"
style="width:1em;margin-right:.5em;" alt="ORCID iD icon"></a><a
href="https://github.com/ajacquey/" target="github.widget" rel="noopener
noreferrer" style="vertical-align:top;"><img src="images/GitHub-Mark-32px.png"
width="16" margin-right=".5em;" alt="GitHub icon id"></a> and [Mauro
Cacace](http://www.gfz-potsdam.de/en/section/basin-modeling/staff/profil/mauro-cacace/)
<a href="https://orcid.org/0000-0001-6101-9918" target="orcid.widget"
rel="noopener noreferrer" style="vertical-align:top;"><img
src="https://orcid.org/sites/default/files/images/orcid_16x16.png"
style="width:1em;margin-right:.5em;" alt="ORCID iD icon"></a><a
href="https://github.com/mcacace" target="github.widget" rel="noopener
noreferrer" style="vertical-align:top;"><img src="images/GitHub-Mark-32px.png"
width="16" margin-right=".5em;" alt="GitHub icon id"></a> at the [GFZ German
Research Centre for Geosciences](http://www.gfz-potsdam.de/en/home/) from the
section [Basin Modelling](http://www.gfz-potsdam.de/en/section/basin-modeling/).
baseurl: "/home" # the subpath of your site, e.g. /blog
url: "https://ajacquey.github.io/Golem/" # the base hostname & protocol for your site
twitter_username: antoine_jacquey 
github_username:  ajacquey

# Build settings
markdown: kramdown
kramdown:
  input: GFM

# Third-party services
# just leave someone empty to disable it
# google_analytics: 
disqus_shortname:

# used this for post_excerpt at index_page
excerpt_separator: <!--description-->
